Vagrant.require_version ">=2.0.0"
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell", path: "setup.sh"
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "-v"
    ansible.config_file = "/home/cmills/Documents/repositories/ansible/ansible.cfg"
    ansible.playbook = "/home/cmills/Documents/repositories/ansible/roles/users/users.yml"
    ansible.limit = "all"
  end
end
