Vagrant.require_version ">=2.0.0"
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "-v"
    ansible.playbook = "/home/cmills/Documents/repositories/ansible/roles/users/users.yml"
    ansible.inventory_path = ".vagrant/provisioners/ansible/inventory/"
    ansible_roles_path = "/home/cmills/Documents/repositories/ansible/roles"
    ansible.limit = "all"
  end
end
