Vagrant.require_version ">=2.0.0"
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.define "elksrv" do |elk|
    elk.vm.provision "shell", path: "setup.sh"
    elk.vm.network "forwarded_port", guest: 9200, host: 8001
    elk.vm.network "forwarded_port", guest: 9300, host: 8002
    elk.vm.network "forwarded_port", guest: 5601, host: 8003
    elk.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.name = "elksrv"
      elk.vm.provision "ansible" do |ansible|
        ansible.verbose = "-v"
        ansible.config_file = "/home/cmills/Documents/repositories/ansible/ansible.cfg"
        ansible.playbook = "/home/cmills/Documents/repositories/ansible/roles/elasticsearch/elasticsearch.yml"
        ansible.limit = "all"
      end
    end
  end

  config.vm.define "logsrv" do |log|
    log.vm.provision "shell", path: "setup.sh"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.name = "logsrv"
      log.vm.provision "ansible" do |ansible|
        ansible.verbose = "-v"
        ansible.config_file = "/home/cmills/Documents/repositories/ansible/ansible.cfg"
        ansible.playbook = "/home/cmills/Documents/repositories/ansible/roles/logstash/logstash.yml"
        ansible.limit = "all"
      end
    end
  end

end
