Vagrant.require_version ">=2.0.0"
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell", path: "setup.sh"
  config.vm.provider "virtualbox" do |vb|
  config.vm.network "forwarded_port", guest: 8080, host: 8001
	vb.memory = "512"
	vb.name = "jenkins-2"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "-v"
    ansible.config_file = "ansible.cfg"
    ansible.playbook = "ansible/roles/jenkins/jenkins.yml"
    ansible.limit = "all"
  end
end
