Vagrant.require_version ">=2.0.0"
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell", path: "shell_scripts/vagrant_env_setup.sh"
  config.vm.provider "virtualbox" do |vb|
  config.vm.network "forwarded_port", guest: 80, host: 8000
	vb.memory = "512"
	vb.name = "grav"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "-vv"
    ansible.config_file = "ansible.cfg"
    ansible.playbook = "ansible/roles/grav-admin/grav-admin.yml"
    ansible.limit = "all"
  end
end
